/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UnauthorizedRouteImport } from './routes/unauthorized'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DemoTanstackQueryRouteImport } from './routes/demo/tanstack-query'
import { Route as AuthenticatedStudentRouteRouteImport } from './routes/_authenticated/student/route'
import { Route as AuthenticatedLecturerRouteRouteImport } from './routes/_authenticated/lecturer/route'
import { Route as AuthenticatedStudentIndexRouteImport } from './routes/_authenticated/student/index'
import { Route as AuthenticatedLecturerIndexRouteImport } from './routes/_authenticated/lecturer/index'
import { Route as AuthenticatedStudentSubjectsRouteImport } from './routes/_authenticated/student/subjects'
import { Route as AuthenticatedStudentAiRouteImport } from './routes/_authenticated/student/ai'
import { Route as AuthenticatedLecturerSubjectsRouteImport } from './routes/_authenticated/lecturer/subjects'
import { Route as AuthenticatedLecturerRegisteredUsersRouteImport } from './routes/_authenticated/lecturer/registered-users'
import { Route as AuthenticatedLecturerManageGradesRouteImport } from './routes/_authenticated/lecturer/manage-grades'
import { Route as AuthenticatedLecturerAssessmentRouteImport } from './routes/_authenticated/lecturer/assessment'
import { Route as AuthenticatedLecturerAiRouteImport } from './routes/_authenticated/lecturer/ai'

const UnauthorizedRoute = UnauthorizedRouteImport.update({
  id: '/unauthorized',
  path: '/unauthorized',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoTanstackQueryRoute = DemoTanstackQueryRouteImport.update({
  id: '/demo/tanstack-query',
  path: '/demo/tanstack-query',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedStudentRouteRoute =
  AuthenticatedStudentRouteRouteImport.update({
    id: '/student',
    path: '/student',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedLecturerRouteRoute =
  AuthenticatedLecturerRouteRouteImport.update({
    id: '/lecturer',
    path: '/lecturer',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedStudentIndexRoute =
  AuthenticatedStudentIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedStudentRouteRoute,
  } as any)
const AuthenticatedLecturerIndexRoute =
  AuthenticatedLecturerIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedLecturerRouteRoute,
  } as any)
const AuthenticatedStudentSubjectsRoute =
  AuthenticatedStudentSubjectsRouteImport.update({
    id: '/subjects',
    path: '/subjects',
    getParentRoute: () => AuthenticatedStudentRouteRoute,
  } as any)
const AuthenticatedStudentAiRoute = AuthenticatedStudentAiRouteImport.update({
  id: '/ai',
  path: '/ai',
  getParentRoute: () => AuthenticatedStudentRouteRoute,
} as any)
const AuthenticatedLecturerSubjectsRoute =
  AuthenticatedLecturerSubjectsRouteImport.update({
    id: '/subjects',
    path: '/subjects',
    getParentRoute: () => AuthenticatedLecturerRouteRoute,
  } as any)
const AuthenticatedLecturerRegisteredUsersRoute =
  AuthenticatedLecturerRegisteredUsersRouteImport.update({
    id: '/registered-users',
    path: '/registered-users',
    getParentRoute: () => AuthenticatedLecturerRouteRoute,
  } as any)
const AuthenticatedLecturerManageGradesRoute =
  AuthenticatedLecturerManageGradesRouteImport.update({
    id: '/manage-grades',
    path: '/manage-grades',
    getParentRoute: () => AuthenticatedLecturerRouteRoute,
  } as any)
const AuthenticatedLecturerAssessmentRoute =
  AuthenticatedLecturerAssessmentRouteImport.update({
    id: '/assessment',
    path: '/assessment',
    getParentRoute: () => AuthenticatedLecturerRouteRoute,
  } as any)
const AuthenticatedLecturerAiRoute = AuthenticatedLecturerAiRouteImport.update({
  id: '/ai',
  path: '/ai',
  getParentRoute: () => AuthenticatedLecturerRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/unauthorized': typeof UnauthorizedRoute
  '/lecturer': typeof AuthenticatedLecturerRouteRouteWithChildren
  '/student': typeof AuthenticatedStudentRouteRouteWithChildren
  '/demo/tanstack-query': typeof DemoTanstackQueryRoute
  '/lecturer/ai': typeof AuthenticatedLecturerAiRoute
  '/lecturer/assessment': typeof AuthenticatedLecturerAssessmentRoute
  '/lecturer/manage-grades': typeof AuthenticatedLecturerManageGradesRoute
  '/lecturer/registered-users': typeof AuthenticatedLecturerRegisteredUsersRoute
  '/lecturer/subjects': typeof AuthenticatedLecturerSubjectsRoute
  '/student/ai': typeof AuthenticatedStudentAiRoute
  '/student/subjects': typeof AuthenticatedStudentSubjectsRoute
  '/lecturer/': typeof AuthenticatedLecturerIndexRoute
  '/student/': typeof AuthenticatedStudentIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/unauthorized': typeof UnauthorizedRoute
  '/demo/tanstack-query': typeof DemoTanstackQueryRoute
  '/lecturer/ai': typeof AuthenticatedLecturerAiRoute
  '/lecturer/assessment': typeof AuthenticatedLecturerAssessmentRoute
  '/lecturer/manage-grades': typeof AuthenticatedLecturerManageGradesRoute
  '/lecturer/registered-users': typeof AuthenticatedLecturerRegisteredUsersRoute
  '/lecturer/subjects': typeof AuthenticatedLecturerSubjectsRoute
  '/student/ai': typeof AuthenticatedStudentAiRoute
  '/student/subjects': typeof AuthenticatedStudentSubjectsRoute
  '/lecturer': typeof AuthenticatedLecturerIndexRoute
  '/student': typeof AuthenticatedStudentIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/unauthorized': typeof UnauthorizedRoute
  '/_authenticated/lecturer': typeof AuthenticatedLecturerRouteRouteWithChildren
  '/_authenticated/student': typeof AuthenticatedStudentRouteRouteWithChildren
  '/demo/tanstack-query': typeof DemoTanstackQueryRoute
  '/_authenticated/lecturer/ai': typeof AuthenticatedLecturerAiRoute
  '/_authenticated/lecturer/assessment': typeof AuthenticatedLecturerAssessmentRoute
  '/_authenticated/lecturer/manage-grades': typeof AuthenticatedLecturerManageGradesRoute
  '/_authenticated/lecturer/registered-users': typeof AuthenticatedLecturerRegisteredUsersRoute
  '/_authenticated/lecturer/subjects': typeof AuthenticatedLecturerSubjectsRoute
  '/_authenticated/student/ai': typeof AuthenticatedStudentAiRoute
  '/_authenticated/student/subjects': typeof AuthenticatedStudentSubjectsRoute
  '/_authenticated/lecturer/': typeof AuthenticatedLecturerIndexRoute
  '/_authenticated/student/': typeof AuthenticatedStudentIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/register'
    | '/unauthorized'
    | '/lecturer'
    | '/student'
    | '/demo/tanstack-query'
    | '/lecturer/ai'
    | '/lecturer/assessment'
    | '/lecturer/manage-grades'
    | '/lecturer/registered-users'
    | '/lecturer/subjects'
    | '/student/ai'
    | '/student/subjects'
    | '/lecturer/'
    | '/student/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/register'
    | '/unauthorized'
    | '/demo/tanstack-query'
    | '/lecturer/ai'
    | '/lecturer/assessment'
    | '/lecturer/manage-grades'
    | '/lecturer/registered-users'
    | '/lecturer/subjects'
    | '/student/ai'
    | '/student/subjects'
    | '/lecturer'
    | '/student'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/login'
    | '/register'
    | '/unauthorized'
    | '/_authenticated/lecturer'
    | '/_authenticated/student'
    | '/demo/tanstack-query'
    | '/_authenticated/lecturer/ai'
    | '/_authenticated/lecturer/assessment'
    | '/_authenticated/lecturer/manage-grades'
    | '/_authenticated/lecturer/registered-users'
    | '/_authenticated/lecturer/subjects'
    | '/_authenticated/student/ai'
    | '/_authenticated/student/subjects'
    | '/_authenticated/lecturer/'
    | '/_authenticated/student/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  LoginRoute: typeof LoginRoute
  RegisterRoute: typeof RegisterRoute
  UnauthorizedRoute: typeof UnauthorizedRoute
  DemoTanstackQueryRoute: typeof DemoTanstackQueryRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/unauthorized': {
      id: '/unauthorized'
      path: '/unauthorized'
      fullPath: '/unauthorized'
      preLoaderRoute: typeof UnauthorizedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/tanstack-query': {
      id: '/demo/tanstack-query'
      path: '/demo/tanstack-query'
      fullPath: '/demo/tanstack-query'
      preLoaderRoute: typeof DemoTanstackQueryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/student': {
      id: '/_authenticated/student'
      path: '/student'
      fullPath: '/student'
      preLoaderRoute: typeof AuthenticatedStudentRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/lecturer': {
      id: '/_authenticated/lecturer'
      path: '/lecturer'
      fullPath: '/lecturer'
      preLoaderRoute: typeof AuthenticatedLecturerRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/student/': {
      id: '/_authenticated/student/'
      path: '/'
      fullPath: '/student/'
      preLoaderRoute: typeof AuthenticatedStudentIndexRouteImport
      parentRoute: typeof AuthenticatedStudentRouteRoute
    }
    '/_authenticated/lecturer/': {
      id: '/_authenticated/lecturer/'
      path: '/'
      fullPath: '/lecturer/'
      preLoaderRoute: typeof AuthenticatedLecturerIndexRouteImport
      parentRoute: typeof AuthenticatedLecturerRouteRoute
    }
    '/_authenticated/student/subjects': {
      id: '/_authenticated/student/subjects'
      path: '/subjects'
      fullPath: '/student/subjects'
      preLoaderRoute: typeof AuthenticatedStudentSubjectsRouteImport
      parentRoute: typeof AuthenticatedStudentRouteRoute
    }
    '/_authenticated/student/ai': {
      id: '/_authenticated/student/ai'
      path: '/ai'
      fullPath: '/student/ai'
      preLoaderRoute: typeof AuthenticatedStudentAiRouteImport
      parentRoute: typeof AuthenticatedStudentRouteRoute
    }
    '/_authenticated/lecturer/subjects': {
      id: '/_authenticated/lecturer/subjects'
      path: '/subjects'
      fullPath: '/lecturer/subjects'
      preLoaderRoute: typeof AuthenticatedLecturerSubjectsRouteImport
      parentRoute: typeof AuthenticatedLecturerRouteRoute
    }
    '/_authenticated/lecturer/registered-users': {
      id: '/_authenticated/lecturer/registered-users'
      path: '/registered-users'
      fullPath: '/lecturer/registered-users'
      preLoaderRoute: typeof AuthenticatedLecturerRegisteredUsersRouteImport
      parentRoute: typeof AuthenticatedLecturerRouteRoute
    }
    '/_authenticated/lecturer/manage-grades': {
      id: '/_authenticated/lecturer/manage-grades'
      path: '/manage-grades'
      fullPath: '/lecturer/manage-grades'
      preLoaderRoute: typeof AuthenticatedLecturerManageGradesRouteImport
      parentRoute: typeof AuthenticatedLecturerRouteRoute
    }
    '/_authenticated/lecturer/assessment': {
      id: '/_authenticated/lecturer/assessment'
      path: '/assessment'
      fullPath: '/lecturer/assessment'
      preLoaderRoute: typeof AuthenticatedLecturerAssessmentRouteImport
      parentRoute: typeof AuthenticatedLecturerRouteRoute
    }
    '/_authenticated/lecturer/ai': {
      id: '/_authenticated/lecturer/ai'
      path: '/ai'
      fullPath: '/lecturer/ai'
      preLoaderRoute: typeof AuthenticatedLecturerAiRouteImport
      parentRoute: typeof AuthenticatedLecturerRouteRoute
    }
  }
}

interface AuthenticatedLecturerRouteRouteChildren {
  AuthenticatedLecturerAiRoute: typeof AuthenticatedLecturerAiRoute
  AuthenticatedLecturerAssessmentRoute: typeof AuthenticatedLecturerAssessmentRoute
  AuthenticatedLecturerManageGradesRoute: typeof AuthenticatedLecturerManageGradesRoute
  AuthenticatedLecturerRegisteredUsersRoute: typeof AuthenticatedLecturerRegisteredUsersRoute
  AuthenticatedLecturerSubjectsRoute: typeof AuthenticatedLecturerSubjectsRoute
  AuthenticatedLecturerIndexRoute: typeof AuthenticatedLecturerIndexRoute
}

const AuthenticatedLecturerRouteRouteChildren: AuthenticatedLecturerRouteRouteChildren =
  {
    AuthenticatedLecturerAiRoute: AuthenticatedLecturerAiRoute,
    AuthenticatedLecturerAssessmentRoute: AuthenticatedLecturerAssessmentRoute,
    AuthenticatedLecturerManageGradesRoute:
      AuthenticatedLecturerManageGradesRoute,
    AuthenticatedLecturerRegisteredUsersRoute:
      AuthenticatedLecturerRegisteredUsersRoute,
    AuthenticatedLecturerSubjectsRoute: AuthenticatedLecturerSubjectsRoute,
    AuthenticatedLecturerIndexRoute: AuthenticatedLecturerIndexRoute,
  }

const AuthenticatedLecturerRouteRouteWithChildren =
  AuthenticatedLecturerRouteRoute._addFileChildren(
    AuthenticatedLecturerRouteRouteChildren,
  )

interface AuthenticatedStudentRouteRouteChildren {
  AuthenticatedStudentAiRoute: typeof AuthenticatedStudentAiRoute
  AuthenticatedStudentSubjectsRoute: typeof AuthenticatedStudentSubjectsRoute
  AuthenticatedStudentIndexRoute: typeof AuthenticatedStudentIndexRoute
}

const AuthenticatedStudentRouteRouteChildren: AuthenticatedStudentRouteRouteChildren =
  {
    AuthenticatedStudentAiRoute: AuthenticatedStudentAiRoute,
    AuthenticatedStudentSubjectsRoute: AuthenticatedStudentSubjectsRoute,
    AuthenticatedStudentIndexRoute: AuthenticatedStudentIndexRoute,
  }

const AuthenticatedStudentRouteRouteWithChildren =
  AuthenticatedStudentRouteRoute._addFileChildren(
    AuthenticatedStudentRouteRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedLecturerRouteRoute: typeof AuthenticatedLecturerRouteRouteWithChildren
  AuthenticatedStudentRouteRoute: typeof AuthenticatedStudentRouteRouteWithChildren
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedLecturerRouteRoute: AuthenticatedLecturerRouteRouteWithChildren,
  AuthenticatedStudentRouteRoute: AuthenticatedStudentRouteRouteWithChildren,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
  UnauthorizedRoute: UnauthorizedRoute,
  DemoTanstackQueryRoute: DemoTanstackQueryRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
